# Generated by Django 4.0.4 on 2022-05-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': ('Кафедра',),
                'verbose_name_plural': 'Кафедри',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Предмет')),
                ('katedra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.katedra')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва університету')),
            ],
            options={
                'verbose_name': 'Університет',
                'verbose_name_plural': 'Університети',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='katedra',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.university'),
        ),
    ]
