# Generated by Django 4.0.4 on 2022-05-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_katedra_subject_university_delete_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katedra',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ugc.university'),
        ),
    ]
