# Generated by Django 4.0.4 on 2022-05-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_katedra_university'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': ('Предмет',), 'verbose_name_plural': 'Предмети'},
        ),
    ]
