# Generated by Django 4.0.4 on 2022-05-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_subject_descr_subject_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
